/**
 * Traduções dos nomes de países, geradas a partir de `CountryTranslate.java`.
 *
 * Mantém o mesmo conjunto de idiomas suportado pela biblioteca
 * (en, pt, es, fr, de, it, ja, ko, zh, ru, ar) e é indexado pelo código ISO
 * (`iso2`) usado em `flag-map.ts`.
 */
export type CountryTranslateLocale =
  | "en"
  | "pt"
  | "es"
  | "fr"
  | "de"
  | "it"
  | "ja"
  | "ko"
  | "zh"
  | "ru"
  | "ar";

export const COUNTRY_TRANSLATIONS: Record<
  string,
  Record<CountryTranslateLocale, string>
> = {
  "ad": { en: "Andorra", pt: "Andorra", es: "Andorra", fr: "Andorre", de: "Andorra", it: "Andorra", ja: "アンドラ", ko: "안도라", zh: "安道尔", ru: "Андорра", ar: "أندورا" },
  "ae": { en: "United Arab Emirates", pt: "Emirados Árabes Unidos", es: "Emiratos Árabes Unidos", fr: "Émirats Arabes Unis", de: "Vereinigte Arabische Emirate", it: "Emirati Arabi Uniti", ja: "アラブ首長国連邦", ko: "아랍에미리트연합", zh: "阿联酋", ru: "ОАЭ", ar: "الإمارات العربية المتحدة" },
  "af": { en: "Afghanistan", pt: "Afeganistão", es: "Afganistán", fr: "Afghanistan", de: "Afghanistan", it: "Afghanistan", ja: "アフガニスタン", ko: "아프가니스탄", zh: "阿富汗", ru: "Афганистан", ar: "أفغانستان" },
  "ag": { en: "Antigua and Barbuda", pt: "Antígua e Barbuda", es: "Antigua y Barbuda", fr: "Antigua-et-Barbuda", de: "Antigua und Barbuda", it: "Antigua e Barbuda", ja: "アンティグア・バーブーダ", ko: "안티구아 바부다", zh: "安提瓜和巴布达", ru: "Антигуа и Барбуда", ar: "أنتيغوا وباربودا" },
  "ai": { en: "Anguilla", pt: "Anguila", es: "Anguila", fr: "Anguilla", de: "Anguilla", it: "Anguilla", ja: "アンギラ", ko: "앙길라", zh: "安圭拉", ru: "Ангилья", ar: "أنغويلا" },
  "al": { en: "Albania", pt: "Albânia", es: "Albania", fr: "Albanie", de: "Albanien", it: "Albania", ja: "アルバニア", ko: "알바니아", zh: "阿尔巴尼亚", ru: "Албания", ar: "ألبانيا" },
  "am": { en: "Armenia", pt: "Arménia", es: "Armenia", fr: "Arménie", de: "Armenien", it: "Armenia", ja: "アルメニア", ko: "아르메니아", zh: "亚美尼亚", ru: "Армения", ar: "أرمينيا" },
  "ao": { en: "Angola", pt: "Angola", es: "Angola", fr: "Angola", de: "Angola", it: "Angola", ja: "アンゴラ", ko: "앙골라", zh: "安哥拉", ru: "Ангола", ar: "أنغولا" },
  "aq": { en: "Antarctica", pt: "Antártida", es: "Antártida", fr: "Antarctique", de: "Antarktis", it: "Antartide", ja: "南極", ko: "안타티카", zh: "南极洲", ru: "Антарктида", ar: "القارة القطبية الجنوبية" },
  "ar": { en: "Argentina", pt: "Argentina", es: "Argentina", fr: "Argentine", de: "Argentinien", it: "Argentina", ja: "アルゼンチン", ko: "아르헨티나", zh: "阿根廷", ru: "Аргентина", ar: "الأرجنتين" },
  "as": { en: "American Samoa", pt: "Samoa Americana", es: "Samoa Americana", fr: "Samoa américaines", de: "Amerikanisch-Samoa", it: "Samoa Americane", ja: "アメリカ領サモア", ko: "아메리칸 사모아", zh: "美属萨摩亚", ru: "Американское Самоа", ar: "ساموا الأمريكية" },
  "at": { en: "Austria", pt: "Áustria", es: "Austria", fr: "Autriche", de: "Österreich", it: "Austria", ja: "オーストリア", ko: "오스트리아", zh: "奥地利", ru: "Австрия", ar: "النمسا" },
  "au": { en: "Australia", pt: "Austrália", es: "Australia", fr: "Australie", de: "Australien", it: "Australia", ja: "オーストラリア", ko: "호주", zh: "澳大利亚", ru: "Австралия", ar: "أستراليا" },
  "aw": { en: "Aruba", pt: "Aruba", es: "Aruba", fr: "Aruba", de: "Aruba", it: "Aruba", ja: "アルバ", ko: "아루바", zh: "阿鲁巴", ru: "Аруба", ar: "أروبا" },
  "ax": { en: "Åland Islands", pt: "Ilhas Åland", es: "Islas Åland", fr: "Åland", de: "Åland", it: "Isole Åland", ja: "オーランド諸島", ko: "올란드 제도", zh: "奥兰", ru: "Аландские острова", ar: "جزر أولاند" },
  "az": { en: "Azerbaijan", pt: "Azerbaijão", es: "Azerbaiyán", fr: "Azerbaïdjan", de: "Aserbaidschan", it: "Azerbaigian", ja: "アゼルバイジャン", ko: "아제르바이잔", zh: "阿塞拜疆", ru: "Азербайджан", ar: "أذربيجان" },
  "ba": { en: "Bosnia and Herzegovina", pt: "Bósnia-Herzegovina", es: "Bosnia y Herzegovina", fr: "Bosnie-Herzégovine", de: "Bosnien und Herzegowina", it: "Bosnia ed Erzegovina", ja: "ボスニア・ヘルツェゴビナ", ko: "보스니아 헤르체고비나", zh: "波黑", ru: "Босния и Герцеговина", ar: "البوسنة والهرسك" },
  "bb": { en: "Barbados", pt: "Barbados", es: "Barbados", fr: "Barbade", de: "Barbados", it: "Barbados", ja: "バルバドス", ko: "바베이도스", zh: "巴巴多斯", ru: "Барбадос", ar: "باربادوس" },
  "bd": { en: "Bangladesh", pt: "Bangladesh", es: "Bangladesh", fr: "Bangladesh", de: "Bangladesch", it: "Bangladesh", ja: "バングラデシュ", ko: "방글라데시", zh: "孟加拉国", ru: "Бангладеш", ar: "بنغلاديش" },
  "be": { en: "Belgium", pt: "Bélgica", es: "Bélgica", fr: "Belgique", de: "Belgien", it: "Belgio", ja: "ベルギー", ko: "벨기에", zh: "比利时", ru: "Бельгия", ar: "بلجيكا" },
  "bf": { en: "Burkina Faso", pt: "Burkina Faso", es: "Burkina Faso", fr: "Burkina Faso", de: "Burkina Faso", it: "Burkina Faso", ja: "ブルキナファソ", ko: "부르키나파소", zh: "布基纳法索", ru: "Буркина-Фасо", ar: "بوركينا فاسو" },
  "bg": { en: "Bulgaria", pt: "Bulgária", es: "Bulgaria", fr: "Bulgarie", de: "Bulgarien", it: "Bulgaria", ja: "ブルガリア", ko: "불가리아", zh: "保加利亚", ru: "Болгария", ar: "بلغاريا" },
  "bh": { en: "Bahrain", pt: "Bahrein", es: "Bahrein", fr: "Bahreïn", de: "Bahrain", it: "Bahrain", ja: "バーレーン", ko: "바레인", zh: "巴林", ru: "Бахрейн", ar: "البحرين" },
  "bi": { en: "Burundi", pt: "Burundi", es: "Burundi", fr: "Burundi", de: "Burundi", it: "Burundi", ja: "ブルンジ", ko: "부룬디", zh: "布隆迪", ru: "Бурунди", ar: "بوروندي" },
  "bj": { en: "Benin", pt: "Benim", es: "Benin", fr: "Bénin", de: "Benin", it: "Benin", ja: "ベナン", ko: "베냉", zh: "贝宁", ru: "Бенин", ar: "بنين" },
  "bl": { en: "Saint Barthélemy", pt: "São Bartolomeu", es: "Saint Barthélemy", fr: "Saint-Barthélemy", de: "Saint-Barthélemy", it: "Saint-Barthélemy", ja: "サン・バルテルミー", ko: "생 바르 텔레 미", zh: "圣巴泰勒米", ru: "Сен-Бартелеми", ar: "سان بارتيلمي" },
  "bm": { en: "Bermuda", pt: "Bermudas", es: "Bermudas", fr: "Bermudes", de: "Bermuda", it: "Bermuda", ja: "バミューダ", ko: "버뮤다", zh: "百慕大", ru: "Бермуды", ar: "برمودا" },
  "bn": { en: "Brunei", pt: "Brunei", es: "Brunei Darussalam", fr: "Brunei Darussalam", de: "Brunei Darussalam", it: "Brunei", ja: "ブルネイ・ダルサラーム", ko: "브루나이", zh: "文莱", ru: "Бруней", ar: "بروناي" },
  "bo": { en: "Bolivia", pt: "Bolívia", es: "Bolivia", fr: "Bolivie", de: "Bolivien", it: "Bolivia", ja: "ボリビア多民族国", ko: "볼리비아", zh: "玻利维亚", ru: "Боливия", ar: "بوليفيا" },
  "bq": { en: "Bonaire", pt: "Países Baixos Caribenhos", es: "Bonaire, San Eustaquio y Saba", fr: "Bonaire, Saint-Eustache et Saba", de: "Bonaire", it: "Isole BES", ja: "ボネール、シント・ユースタティウスおよびサバ", ko: "보네르,신트유스타티우스,사바", zh: "荷兰加勒比区", ru: "Бонэйр, Синт-Эстатиус и Саба", ar: "الجزر الكاريبية الهولندية" },
  "br": { en: "Brazil", pt: "Brasil", es: "Brasil", fr: "Brésil", de: "Brasilien", it: "Brasile", ja: "ブラジル", ko: "브라질", zh: "巴西", ru: "Бразилия", ar: "البرازيل" },
  "bs": { en: "Bahamas", pt: "Bahamas", es: "Bahamas", fr: "Bahamas", de: "Bahamas", it: "Bahamas", ja: "バハマ", ko: "바하마", zh: "巴哈马", ru: "Багамы", ar: "باهاماس" },
  "bt": { en: "Bhutan", pt: "Butão", es: "Bután", fr: "Bhoutan", de: "Bhutan", it: "Bhutan", ja: "ブータン", ko: "부탄", zh: "不丹", ru: "Бутан", ar: "بوتان" },
  "bv": { en: "Bouvet Island", pt: "Ilha Bouvet", es: "Isla Bouvet", fr: "Île Bouvet", de: "Bouvetinsel", it: "Isola Bouvet", ja: "ブーベ島", ko: "부베섬", zh: "布韦岛", ru: "Остров Буве", ar: "جزيرة بوفيه" },
  "bw": { en: "Botswana", pt: "Botsuana", es: "Botswana", fr: "Botswana", de: "Botswana", it: "Botswana", ja: "ボツワナ", ko: "보츠와나", zh: "博茨瓦纳", ru: "Ботсвана", ar: "بوتسوانا" },
  "by": { en: "Belarus", pt: "Bielorrússia", es: "Bielorrusia", fr: "Biélorussie", de: "Belarus", it: "Bielorussia", ja: "ベラルーシ", ko: "벨라루스", zh: "白俄罗斯", ru: "Беларусь", ar: "روسيا البيضاء" },
  "bz": { en: "Belize", pt: "Belize", es: "Belice", fr: "Belize", de: "Belize", it: "Belize", ja: "ベリーズ", ko: "벨리즈", zh: "伯利兹", ru: "Белиз", ar: "بليز" },
  "ca": { en: "Canada", pt: "Canadá", es: "Canadá", fr: "Canada", de: "Kanada", it: "Canada", ja: "カナダ", ko: "캐나다", zh: "加拿大", ru: "Канада", ar: "كندا" },
  "cc": { en: "Cocos Islands", pt: "Ilhas Cocos (Keeling)", es: "Islas Cocos (Keeling)", fr: "Îles Cocos", de: "Kokosinseln", it: "Isole Cocos e Keeling", ja: "ココス（キーリング）諸島", ko: "코코스 제도", zh: "科科斯（基林）群岛", ru: "Кокосовые острова", ar: "جزر كوكوس" },
  "cd": { en: "DR Congo", pt: "República Popular do Congo", es: "Congo (República Democrática del)", fr: "République démocratique du Congo", de: "Kongo", it: "Repubblica Democratica del Congo", ja: "コンゴ民主共和国", ko: "콩고 민주 공화국", zh: "刚果（金）", ru: "Демократическая Республика Конго", ar: "جمهورية الكونغو الديمقراطية" },
  "cf": { en: "Central African Republic", pt: "República Centro-Africana", es: "República Centroafricana", fr: "République Centrafricaine", de: "Zentralafrikanische Republik", it: "Repubblica Centrafricana", ja: "中央アフリカ共和国", ko: "중앙 아프리카", zh: "中非", ru: "ЦАР", ar: "جمهورية أفريقيا الوسطى" },
  "cg": { en: "Congo", pt: "República Democrática do Congo", es: "Congo", fr: "République du Congo", de: "Republik Kongo", it: "Repubblica del Congo", ja: "コンゴ共和国", ko: "콩고", zh: "刚果（布）", ru: "Республика Конго", ar: "جمهورية الكونغو" },
  "ch": { en: "Switzerland", pt: "Suíça", es: "Suiza", fr: "Suisse", de: "Schweiz", it: "Svizzera", ja: "スイス", ko: "스위스", zh: "瑞士", ru: "Швейцария", ar: "سويسرا" },
  "ci": { en: "Côte d'Ivoire", pt: "Costa do Marfim", es: "Costa de Marfil", fr: "Côte-d'Ivoire", de: "Elfenbeinküste", it: "Costa d'Avorio", ja: "コートジボワール", ko: "코트디부아르", zh: "科特迪瓦", ru: "Кот-д’Ивуар", ar: "ساحل العاج" },
  "ck": { en: "Cook Islands", pt: "Ilhas Cook", es: "Islas Cook", fr: "Îles Cook", de: "Cookinseln", it: "Isole Cook", ja: "クック諸島", ko: "쿡 제도", zh: "库克群岛", ru: "Острова Кука", ar: "جزر كوك" },
  "cl": { en: "Chile", pt: "Chile", es: "Chile", fr: "Chili", de: "Chile", it: "Cile", ja: "チリ", ko: "칠레", zh: "智利", ru: "Чили", ar: "تشيلي" },
  "cm": { en: "Cameroon", pt: "Camarões", es: "Camerún", fr: "Cameroun", de: "Kamerun", it: "Camerun", ja: "カメルーン", ko: "카메룬", zh: "喀麦隆", ru: "Камерун", ar: "الكاميرون" },
  "cn": { en: "China", pt: "China", es: "China", fr: "Chine", de: "China", it: "Cina", ja: "中華人民共和国", ko: "중국", zh: "中国", ru: "КНР (Китайская Народная Республика)", ar: "الصين" },
  "co": { en: "Colombia", pt: "Colômbia", es: "Colombia", fr: "Colombie", de: "Kolumbien", it: "Colombia", ja: "コロンビア", ko: "콜롬비아", zh: "哥伦比亚", ru: "Колумбия", ar: "كولومبيا" },
  "cr": { en: "Costa Rica", pt: "Costa Rica", es: "Costa Rica", fr: "Costa Rica", de: "Costa Rica", it: "Costa Rica", ja: "コスタリカ", ko: "코스타리카", zh: "哥斯达黎加", ru: "Коста-Рика", ar: "كوستاريكا" },
  "cu": { en: "Cuba", pt: "Cuba", es: "Cuba", fr: "Cuba", de: "Kuba", it: "Cuba", ja: "キューバ", ko: "쿠바", zh: "古巴", ru: "Куба", ar: "كوبا" },
  "cv": { en: "Cape Verde", pt: "Cabo Verde", es: "Cabo Verde", fr: "Cap-Vert", de: "Kap Verde", it: "Capo Verde", ja: "カーボベルデ", ko: "카보 베르데", zh: "佛得角", ru: "Кабо-Верде", ar: "الرأس الأخضر" },
  "cw": { en: "Curaçao", pt: "Curaçao", es: "Curaçao", fr: "Curaçao", de: "Curaçao", it: "Curaçao", ja: "キュラソー", ko: "큐라소", zh: "库拉索", ru: "Кюрасао", ar: "كوراساو" },
  "cx": { en: "Christmas Island", pt: "Ilha de Natal", es: "Isla de Navidad", fr: "Île Christmas", de: "Weihnachtsinsel", it: "Isola del Natale", ja: "クリスマス島", ko: "크리스마스섬", zh: "圣诞岛", ru: "Остров Рождества", ar: "جزيرة عيد الميلاد" },
  "cy": { en: "Cyprus", pt: "Chipre", es: "Chipre", fr: "Chypre", de: "Zypern", it: "Cipro", ja: "キプロス", ko: "사이프러스", zh: "塞浦路斯", ru: "Кипр", ar: "قبرص" },
  "cz": { en: "Czech Republic", pt: "Chéquia", es: "República Checa", fr: "République Tchèque", de: "Tschechische Republik", it: "Repubblica Ceca", ja: "チェコ", ko: "체코공화국", zh: "捷克", ru: "Чехия", ar: "جمهورية التشيك" },
  "de": { en: "Germany", pt: "Alemanha", es: "Alemania", fr: "Allemagne", de: "Deutschland", it: "Germania", ja: "ドイツ", ko: "독일", zh: "德国", ru: "Германия", ar: "ألمانيا" },
  "dj": { en: "Djibouti", pt: "Djibouti", es: "Yibuti", fr: "Djibouti", de: "Dschibuti", it: "Gibuti", ja: "ジブチ", ko: "지부티", zh: "吉布提", ru: "Джибути", ar: "جيبوتي" },
  "dk": { en: "Denmark", pt: "Dinamarca", es: "Dinamarca", fr: "Danemark", de: "Dänemark", it: "Danimarca", ja: "デンマーク", ko: "덴마크", zh: "丹麦", ru: "Дания", ar: "الدنمارك" },
  "dm": { en: "Dominica", pt: "Dominica", es: "Dominica", fr: "Dominique", de: "Dominica", it: "Dominica", ja: "ドミニカ国", ko: "도미니카 연방", zh: "多米尼克", ru: "Доминика", ar: "دومينيكا" },
  "do": { en: "Dominican Republic", pt: "República Dominicana", es: "República Dominicana", fr: "République Dominicaine", de: "Dominikanische Republik", it: "Repubblica Dominicana", ja: "ドミニカ共和国", ko: "도미니카 공화국", zh: "多米尼加", ru: "Доминиканская Республика", ar: "جمهورية الدومينيكان" },
  "dz": { en: "Algeria", pt: "Argélia", es: "Argelia", fr: "Algérie", de: "Algerien", it: "Algeria", ja: "アルジェリア", ko: "알제리", zh: "阿尔及利亚", ru: "Алжир", ar: "الجزائر" },
  "ec": { en: "Ecuador", pt: "Equador", es: "Ecuador", fr: "Équateur", de: "Ecuador", it: "Ecuador", ja: "エクアドル", ko: "에콰도르", zh: "厄瓜多尔", ru: "Эквадор", ar: "الإكوادور" },
  "ee": { en: "Estonia", pt: "Estónia", es: "Estonia", fr: "Estonie", de: "Estland", it: "Estonia", ja: "エストニア", ko: "에스토니아", zh: "爱沙尼亚", ru: "Эстония", ar: "إستونيا" },
  "eg": { en: "Egypt", pt: "Egito", es: "Egipto", fr: "Égypte", de: "Ägypten", it: "Egitto", ja: "エジプト", ko: "이집트", zh: "埃及", ru: "Египет", ar: "مصر" },
  "er": { en: "Eritrea", pt: "Eritreia", es: "Eritrea", fr: "Érythrée", de: "Eritrea", it: "Eritrea", ja: "エリトリア", ko: "에리트레아", zh: "厄立特里亚", ru: "Эритрея", ar: "إريتريا" },
  "es": { en: "Spain", pt: "Espanha", es: "España", fr: "Espagne", de: "Spanien", it: "Spagna", ja: "スペイン", ko: "스페인", zh: "西班牙", ru: "Испания", ar: "إسبانيا" },
  "et": { en: "Ethiopia", pt: "Etiópia", es: "Etiopía", fr: "Éthiopie", de: "Äthiopien", it: "Etiopia", ja: "エチオピア", ko: "이디오피아", zh: "埃塞俄比亚", ru: "Эфиопия", ar: "إثيوبيا" },
  "fi": { en: "Finland", pt: "Finlândia", es: "Finlandia", fr: "Finlande", de: "Finnland", it: "Finlandia", ja: "フィンランド", ko: "핀란드", zh: "芬兰", ru: "Финляндия", ar: "فنلندا" },
  "fj": { en: "Fiji", pt: "Fiji", es: "Fiji", fr: "Fidji", de: "Fidschi", it: "Figi", ja: "フィジー", ko: "피지", zh: "斐济", ru: "Фиджи", ar: "فيجي" },
  "fk": { en: "Falkland Islands", pt: "Ilhas Malvinas", es: "Islas Malvinas", fr: "Îles Malouines", de: "Falklandinseln", it: "Isole Falkland", ja: "フォークランド（マルビナス）諸島", ko: "포클랜드섬", zh: "福克兰群岛", ru: "Фолклендские острова", ar: "جزر فوكلاند" },
  "fm": { en: "Micronesia", pt: "Micronésia", es: "Micronesia", fr: "Micronésie", de: "Mikronesien", it: "Stati Federati di Micronesia", ja: "ミクロネシア連邦", ko: "미크로네시아", zh: "密克罗尼西亚联邦", ru: "Микронезия", ar: "ولايات ميكرونيسيا المتحدة" },
  "fo": { en: "Faroe Islands", pt: "Ilhas Faroé", es: "Islas Feroe", fr: "Îles Féroé", de: "Färöer", it: "Isole Fær Øer", ja: "フェロー諸島", ko: "페로 군도", zh: "法罗群岛", ru: "Фареры", ar: "جزر فارو" },
  "fr": { en: "France", pt: "França", es: "Francia", fr: "France", de: "Frankreich", it: "Francia", ja: "フランス", ko: "프랑스", zh: "法国", ru: "Франция", ar: "فرنسا" },
  "ga": { en: "Gabon", pt: "Gabão", es: "Gabón", fr: "Gabon", de: "Gabun", it: "Gabon", ja: "ガボン", ko: "가봉", zh: "加蓬", ru: "Габон", ar: "الغابون" },
  "gb": { en: "United Kingdom", pt: "Reino Unido", es: "Reino Unido", fr: "Royaume-Uni", de: "Vereinigtes Königreich", it: "Regno Unito", ja: "イギリス", ko: "영국", zh: "英国", ru: "Великобритания", ar: "المملكة المتحدة" },
  "gd": { en: "Grenada", pt: "Granada", es: "Granada", fr: "Grenade", de: "Grenada", it: "Grenada", ja: "グレナダ", ko: "그레나다", zh: "格林纳达", ru: "Гренада", ar: "غرينادا" },
  "ge": { en: "Georgia", pt: "Geórgia", es: "Georgia", fr: "Géorgie", de: "Georgien", it: "Georgia", ja: "ジョージア", ko: "그루지아", zh: "格鲁吉亚", ru: "Грузия", ar: "جورجيا" },
  "gf": { en: "French Guiana", pt: "Guiana Francesa", es: "Guayana Francesa", fr: "Guyane française", de: "Französisch-Guayana", it: "Guyana Francese", ja: "フランス領ギアナ", ko: "프랑스령 기아나", zh: "法属圭亚那", ru: "Гвиана", ar: "غويانا الفرنسية" },
  "gg": { en: "Guernsey", pt: "Guernsey", es: "Guernsey", fr: "Guernesey", de: "Guernsey", it: "Guernsey", ja: "ガーンジー", ko: "건지", zh: "根西", ru: "Гернси", ar: "غيرنزي" },
  "gh": { en: "Ghana", pt: "Gana", es: "Ghana", fr: "Ghana", de: "Ghana", it: "Ghana", ja: "ガーナ", ko: "가나", zh: "加纳", ru: "Гана", ar: "غانا" },
  "gi": { en: "Gibraltar", pt: "Gibraltar", es: "Gibraltar", fr: "Gibraltar", de: "Gibraltar", it: "Gibilterra", ja: "ジブラルタル", ko: "지브랄타", zh: "直布罗陀", ru: "Гибралтар", ar: "جبل طارق" },
  "gl": { en: "Greenland", pt: "Gronelândia", es: "Groenlandia", fr: "Groenland", de: "Grönland", it: "Groenlandia", ja: "グリーンランド", ko: "그린랜드", zh: "格陵兰", ru: "Гренландия", ar: "جرينلاند" },
  "gm": { en: "Gambia", pt: "Gâmbia", es: "Gambia", fr: "Gambie", de: "Gambia", it: "Gambia", ja: "ガンビア", ko: "감비아", zh: "冈比亚", ru: "Гамбия", ar: "غامبيا" },
  "gn": { en: "Guinea", pt: "Guiné", es: "Guinea", fr: "Guinée", de: "Guinea", it: "Guinea", ja: "ギニア", ko: "기니", zh: "几内亚", ru: "Гвинея", ar: "غينيا" },
  "gp": { en: "Guadeloupe", pt: "Guadalupe", es: "Guadalupe", fr: "Guadeloupe", de: "Guadeloupe", it: "Guadalupa", ja: "グアドループ", ko: "과들루프", zh: "瓜德罗普", ru: "Гваделупа", ar: "غوادلوب" },
  "gq": { en: "Equatorial Guinea", pt: "Guiné Equatorial", es: "Guinea Ecuatorial", fr: "Guinée équatoriale", de: "Äquatorialguinea", it: "Guinea Equatoriale", ja: "赤道ギニア", ko: "적도 기니", zh: "赤道几内亚", ru: "Экваториальная Гвинея", ar: "غينيا الاستوائية" },
  "gr": { en: "Greece", pt: "Grécia", es: "Grecia", fr: "Grèce", de: "Griechenland", it: "Grecia", ja: "ギリシャ", ko: "그리스", zh: "希腊", ru: "Греция", ar: "اليونان" },
  "gs": { en: "South Georgia and the South Sandwich Islands", pt: "Geórgia do Sul e Ilhas Sandwich do Sul", es: "Georgia del Sur y las Islas Sandwich del Sur", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", de: "Südgeorgien und die Südlichen Sandwichinseln", it: "Georgia del Sud e isole Sandwich meridionali", ja: "サウスジョージア・サウスサンドウィッチ諸島", ko: "남조지아 군도", zh: "南乔治亚和南桑威奇群岛", ru: "Южная Георгия и Южные Сандвичевы Острова", ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية" },
  "gt": { en: "Guatemala", pt: "Guatemala", es: "Guatemala", fr: "Guatemala", de: "Guatemala", it: "Guatemala", ja: "グアテマラ", ko: "과테말라", zh: "危地马拉", ru: "Гватемала", ar: "غواتيمالا" },
  "gu": { en: "Guam", pt: "Guam", es: "Guam", fr: "Guam", de: "Guam", it: "Guam", ja: "グアム", ko: "괌", zh: "关岛", ru: "Гуам", ar: "غوام" },
  "gw": { en: "Guinea-Bissau", pt: "Guiné-Bissau", es: "Guinea Bissau", fr: "Guinée-Bissau", de: "Guinea-Bissau", it: "Guinea-Bissau", ja: "ギニアビサウ", ko: "기네비쏘", zh: "几内亚比绍", ru: "Гвинея-Бисау", ar: "غينيا بيساو" },
  "gy": { en: "Guyana", pt: "Guiana", es: "Guyana", fr: "Guyana", de: "Guyana", it: "Guyana", ja: "ガイアナ", ko: "가이아나", zh: "圭亚那", ru: "Гайана", ar: "غيانا" },
  "hk": { en: "Hong Kong", pt: "Hong Kong", es: "Hong Kong", fr: "Hong Kong", de: "Hongkong", it: "Hong Kong", ja: "香港", ko: "홍콩", zh: "香港", ru: "Гонконг", ar: "هونغ كونغ" },
  "hm": { en: "Heard Island and McDonald Islands", pt: "Ilha Heard e Ilhas McDonald", es: "Heard e Islas McDonald", fr: "Îles Heard-et-MacDonald", de: "Heard und McDonaldinseln", it: "Isole Heard e McDonald", ja: "ハード島とマクドナルド諸島", ko: "허드 맥도날드 군도", zh: "赫德岛和麦克唐纳群岛", ru: "Херд и Макдональд", ar: "جزيرة هيرد وجزر ماكدونالد" },
  "hn": { en: "Honduras", pt: "Honduras", es: "Honduras", fr: "Honduras", de: "Honduras", it: "Honduras", ja: "ホンジュラス", ko: "온두라스", zh: "洪都拉斯", ru: "Гондурас", ar: "هندوراس" },
  "hr": { en: "Croatia", pt: "Croácia", es: "Croacia", fr: "Croatie", de: "Kroatien", it: "Croazia", ja: "クロアチア", ko: "크로아티아", zh: "克罗地亚", ru: "Хорватия", ar: "كرواتيا" },
  "ht": { en: "Haiti", pt: "Haiti", es: "Haití", fr: "Haïti", de: "Haiti", it: "Haiti", ja: "ハイチ", ko: "아이티", zh: "海地", ru: "Гаити", ar: "هايتي" },
  "hu": { en: "Hungary", pt: "Hungria", es: "Hungría", fr: "Hongrie", de: "Ungarn", it: "Ungheria", ja: "ハンガリー", ko: "헝가리", zh: "匈牙利", ru: "Венгрия", ar: "المجر" },
  "id": { en: "Indonesia", pt: "Indonésia", es: "Indonesia", fr: "Indonésie", de: "Indonesien", it: "Indonesia", ja: "インドネシア", ko: "인도네시아", zh: "印尼", ru: "Индонезия", ar: "إندونيسيا" },
  "ie": { en: "Ireland", pt: "Irlanda", es: "Irlanda", fr: "Irlande", de: "Irland", it: "Irlanda", ja: "アイルランド", ko: "아일랜드", zh: "爱尔兰", ru: "Ирландия", ar: "أيرلندا" },
  "il": { en: "Israel", pt: "Israel", es: "Israel", fr: "Israël", de: "Israel", it: "Israele", ja: "イスラエル", ko: "이스라엘", zh: "以色列", ru: "Израиль", ar: "إسرائيل" },
  "im": { en: "Isle of Man", pt: "Ilha de Man", es: "Isla de Man", fr: "Île de Man", de: "Insel Man", it: "Isola di Man", ja: "マン島", ko: "맨섬", zh: "马恩岛", ru: "Остров Мэн", ar: "جزيرة مان" },
  "in": { en: "India", pt: "Índia", es: "India", fr: "Inde", de: "Indien", it: "India", ja: "インド", ko: "인도", zh: "印度", ru: "Индия", ar: "الهند" },
  "io": { en: "British Indian Ocean Territory", pt: "Território Britânico do Oceano Índico", es: "Territorio Británico del Océano Índico", fr: "Océan Indien Britannique", de: "Britisches Territorium im Indischen Ozean", it: "Territori Britannici dell'Oceano Indiano", ja: "イギリス領インド洋地域", ko: "영인도 제도", zh: "英属印度洋领地", ru: "Британская территория в Индийском океане", ar: "إقليم المحيط الهندي البريطاني" },
  "iq": { en: "Iraq", pt: "Iraque", es: "Iraq", fr: "Irak", de: "Irak", it: "Iraq", ja: "イラク", ko: "이라크", zh: "伊拉克", ru: "Ирак", ar: "العراق" },
  "ir": { en: "Iran", pt: "Irão", es: "Irán", fr: "Iran", de: "Iran", it: "Iran", ja: "イラン・イスラム共和国", ko: "이란", zh: "伊朗", ru: "Иран", ar: "إيران" },
  "is": { en: "Iceland", pt: "Islândia", es: "Islandia", fr: "Islande", de: "Island", it: "Islanda", ja: "アイスランド", ko: "아이슬란드", zh: "冰岛", ru: "Исландия", ar: "آيسلندا" },
  "it": { en: "Italy", pt: "Itália", es: "Italia", fr: "Italie", de: "Italien", it: "Italia", ja: "イタリア", ko: "이탈리아", zh: "意大利", ru: "Италия", ar: "إيطاليا" },
  "je": { en: "Jersey", pt: "Jersey", es: "Jersey", fr: "Jersey", de: "Jersey", it: "Jersey", ja: "ジャージー", ko: "저지", zh: "泽西", ru: "Джерси", ar: "جيرزي" },
  "jm": { en: "Jamaica", pt: "Jamaica", es: "Jamaica", fr: "Jamaïque", de: "Jamaika", it: "Giamaica", ja: "ジャマイカ", ko: "자메이카", zh: "牙买加", ru: "Ямайка", ar: "جامايكا" },
  "jo": { en: "Jordan", pt: "Jordânia", es: "Jordania", fr: "Jordanie", de: "Jordanien", it: "Giordania", ja: "ヨルダン", ko: "요르단", zh: "约旦", ru: "Иордания", ar: "الأردن" },
  "jp": { en: "Japan", pt: "Japão", es: "Japón", fr: "Japon", de: "Japan", it: "Giappone", ja: "日本", ko: "일본", zh: "日本", ru: "Япония", ar: "اليابان" },
  "ke": { en: "Kenya", pt: "Quénia", es: "Kenia", fr: "Kenya", de: "Kenia", it: "Kenya", ja: "ケニア", ko: "케냐", zh: "肯尼亚", ru: "Кения", ar: "كينيا" },
  "kg": { en: "Kyrgyzstan", pt: "Quirguistão", es: "Kirguistán", fr: "Kirghizistan", de: "Kirgisistan", it: "Kirghizistan", ja: "キルギス", ko: "키르키즈스탄", zh: "吉尔吉斯斯坦", ru: "Киргизия", ar: "قيرغيزستان" },
  "kh": { en: "Cambodia", pt: "Camboja", es: "Camboya", fr: "Cambodge", de: "Kambodscha", it: "Cambogia", ja: "カンボジア", ko: "캄보디아", zh: "柬埔寨", ru: "Камбоджа", ar: "كمبوديا" },
  "ki": { en: "Kiribati", pt: "Quiribati", es: "Kiribati", fr: "Kiribati", de: "Kiribati", it: "Kiribati", ja: "キリバス", ko: "키르바시", zh: "基里巴斯", ru: "Кирибати", ar: "كيريباتي" },
  "km": { en: "Comoros", pt: "Comores", es: "Comoras", fr: "Comores", de: "Komoren", it: "Comore", ja: "コモロ", ko: "코모로", zh: "科摩罗", ru: "Коморы", ar: "جزر القمر" },
  "kn": { en: "Saint Kitts and Nevis", pt: "São Cristóvão e Neves", es: "Saint Kitts y Nevis", fr: "Saint-Christophe-et-Niévès", de: "St. Kitts und Nevis", it: "Saint Kitts e Nevis", ja: "セントクリストファー・ネイビス", ko: "세인트 키츠 네비스", zh: "圣基茨和尼维斯", ru: "Сент-Китс и Невис", ar: "سانت كيتس ونيفيس" },
  "kp": { en: "North Korea", pt: "Coreia do Norte", es: "República Popular Democrática de Corea", fr: "Corée du Nord", de: "Nordkorea", it: "Corea del Nord", ja: "朝鮮民主主義人民共和国", ko: "북한", zh: "朝鲜", ru: "КНДР (Корейская Народно-Демократическая Республика)", ar: "كوريا الشمالية" },
  "kr": { en: "South Korea", pt: "Coreia do Sul", es: "República de Corea", fr: "Corée du Sud", de: "Südkorea", it: "Corea del Sud", ja: "大韓民国", ko: "대한민국", zh: "韩国", ru: "Республика Корея", ar: "كوريا الجنوبية" },
  "kw": { en: "Kuwait", pt: "Koweit", es: "Kuwait", fr: "Koweït", de: "Kuwait", it: "Kuwait", ja: "クウェート", ko: "쿠웨이트", zh: "科威特", ru: "Кувейт", ar: "الكويت" },
  "ky": { en: "Cayman Islands", pt: "Ilhas Caimão", es: "Islas Caimán", fr: "Îles Caïmans", de: "Kaimaninseln", it: "Isole Cayman", ja: "ケイマン諸島", ko: "케이맨섬", zh: "开曼群岛", ru: "Острова Кайман", ar: "جزر كايمان" },
  "kz": { en: "Kazakhstan", pt: "Cazaquistão", es: "Kazajistán", fr: "Kazakhstan", de: "Kasachstan", it: "Kazakistan", ja: "カザフスタン", ko: "카자흐스탄", zh: "哈萨克斯坦", ru: "Казахстан", ar: "كازاخستان" },
  "la": { en: "Laos", pt: "Laos", es: "República Democrática Popular de Lao", fr: "Laos", de: "Laos", it: "Laos", ja: "ラオス人民民主共和国", ko: "라오스", zh: "老挝", ru: "Лаос", ar: "لاوس" },
  "lb": { en: "Lebanon", pt: "Líbano", es: "Líbano", fr: "Liban", de: "Libanon", it: "Libano", ja: "レバノン", ko: "레바논", zh: "黎巴嫩", ru: "Ливан", ar: "لبنان" },
  "lc": { en: "Saint Lucia", pt: "Santa Lúcia", es: "Santa Lucía", fr: "Sainte-Lucie", de: "St. Lucia", it: "Santa Lucia", ja: "セントルシア", ko: "세인트 루시아", zh: "圣卢西亚", ru: "Сент-Люсия", ar: "سانت لوسيا" },
  "li": { en: "Liechtenstein", pt: "Liechtenstein", es: "Liechtenstein", fr: "Liechtenstein", de: "Liechtenstein", it: "Liechtenstein", ja: "リヒテンシュタイン", ko: "리히텐슈타인", zh: "列支敦士登", ru: "Лихтенштейн", ar: "ليختنشتاين" },
  "lk": { en: "Sri Lanka", pt: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka", de: "Sri Lanka", it: "Sri Lanka", ja: "スリランカ", ko: "스리랑카", zh: "斯里兰卡", ru: "Шри-Ланка", ar: "سريلانكا" },
  "lr": { en: "Liberia", pt: "Libéria", es: "Liberia", fr: "Libéria", de: "Liberia", it: "Liberia", ja: "リベリア", ko: "라이베리아", zh: "利比里亚", ru: "Либерия", ar: "ليبيريا" },
  "ls": { en: "Lesotho", pt: "Lesoto", es: "Lesoto", fr: "Lesotho", de: "Lesotho", it: "Lesotho", ja: "レソト", ko: "레소토", zh: "莱索托", ru: "Лесото", ar: "ليسوتو" },
  "lt": { en: "Lithuania", pt: "Lituânia", es: "Lituania", fr: "Lituanie", de: "Litauen", it: "Lituania", ja: "リトアニア", ko: "리투아니아", zh: "立陶宛", ru: "Литва", ar: "ليتوانيا" },
  "lu": { en: "Luxembourg", pt: "Luxemburgo", es: "Luxemburgo", fr: "Luxembourg", de: "Luxemburg", it: "Lussemburgo", ja: "ルクセンブルク", ko: "룩셈부르크", zh: "卢森堡", ru: "Люксембург", ar: "لوكسمبورغ" },
  "lv": { en: "Latvia", pt: "Letónia", es: "Letonia", fr: "Lettonie", de: "Lettland", it: "Lettonia", ja: "ラトビア", ko: "라트비아", zh: "拉脱维亚", ru: "Латвия", ar: "لاتفيا" },
  "ly": { en: "Libya", pt: "Líbia", es: "Libia", fr: "Libye", de: "Libyen", it: "Libia", ja: "リビア", ko: "리비아", zh: "利比亚", ru: "Ливия", ar: "ليبيا" },
  "ma": { en: "Morocco", pt: "Marrocos", es: "Marruecos", fr: "Maroc", de: "Marokko", it: "Marocco", ja: "モロッコ", ko: "모로코", zh: "摩洛哥", ru: "Марокко", ar: "المغرب" },
  "mc": { en: "Monaco", pt: "Mónaco", es: "Mónaco", fr: "Monaco", de: "Monaco", it: "Monaco", ja: "モナコ", ko: "모나코", zh: "摩纳哥", ru: "Монако", ar: "موناكو" },
  "md": { en: "Moldova", pt: "Moldávia", es: "Moldavia", fr: "Moldavie", de: "Moldawien", it: "Moldavia", ja: "モルドバ共和国", ko: "몰도바", zh: "摩尔多瓦", ru: "Молдавия", ar: "مولدوفا" },
  "me": { en: "Montenegro", pt: "Montenegro", es: "Montenegro", fr: "Monténégro", de: "Montenegro", it: "Montenegro", ja: "モンテネグロ", ko: "몬테네그로", zh: "黑山", ru: "Черногория", ar: "الجبل الأسود" },
  "mf": { en: "Saint Martin", pt: "São Martinho", es: "Saint Martin (francesa)", fr: "Saint-Martin (partie française)", de: "Saint-Martin", it: "Saint-Martin", ja: "サン・マルタン（フランス領）", ko: "세인트 마틴 (프랑스어 부분)", zh: "法属圣马丁", ru: "Сен-Мартен", ar: "سانت مارتن (الجزء الفرنسي)" },
  "mg": { en: "Madagascar", pt: "Madagáscar", es: "Madagascar", fr: "Madagascar", de: "Madagaskar", it: "Madagascar", ja: "マダガスカル", ko: "마다가스카르", zh: "马达加斯加", ru: "Мадагаскар", ar: "مدغشقر" },
  "mh": { en: "Marshall Islands", pt: "Ilhas Marshall", es: "Islas Marshall", fr: "Îles Marshall", de: "Marshallinseln", it: "Isole Marshall", ja: "マーシャル諸島", ko: "마샬군도", zh: "马绍尔群岛", ru: "Маршалловы Острова", ar: "جزر مارشال" },
  "mk": { en: "North Macedonia", pt: "Macedónia do Norte", es: "Macedonia del Norte", fr: "Macédoine du Nord", de: "Nordmazedonien", it: "Macedonia del Nord", ja: "北マケドニア", ko: "마케도니아", zh: "北马其顿", ru: "Северная Македония", ar: "مقدونيا الشمالية" },
  "ml": { en: "Mali", pt: "Mali", es: "Malí", fr: "Mali", de: "Mali", it: "Mali", ja: "マリ", ko: "말리", zh: "马里", ru: "Мали", ar: "مالي" },
  "mm": { en: "Myanmar", pt: "Mianmar (Birmânia)", es: "Myanmar", fr: "Myanmar", de: "Myanmar", it: "Birmania  Myanmar", ja: "ミャンマー", ko: "미얀마", zh: "缅甸", ru: "Мьянма", ar: "بورما" },
  "mn": { en: "Mongolia", pt: "Mongólia", es: "Mongolia", fr: "Mongolie", de: "Mongolei", it: "Mongolia", ja: "モンゴル", ko: "몽골", zh: "蒙古", ru: "Монголия", ar: "منغوليا" },
  "mo": { en: "Macau", pt: "Macau", es: "Macao", fr: "Macao", de: "Macao", it: "Macao", ja: "マカオ", ko: "마카오", zh: "澳门", ru: "Макао", ar: "ماكاو" },
  "mp": { en: "Northern Mariana Islands", pt: "Ilhas Marianas do Norte", es: "Islas Marianas del Norte", fr: "Îles Mariannes du Nord", de: "Nördliche Marianen", it: "Isole Marianne Settentrionali", ja: "北マリアナ諸島", ko: "북마리아나 군도", zh: "北马里亚纳群岛", ru: "Северные Марианские Острова", ar: "جزر ماريانا الشمالية" },
  "mq": { en: "Martinique", pt: "Martinica", es: "Martinica", fr: "Martinique", de: "Martinique", it: "Martinica", ja: "マルティニーク", ko: "마르티니크", zh: "马提尼克", ru: "Мартиника", ar: "مارتينيك" },
  "mr": { en: "Mauritania", pt: "Mauritânia", es: "Mauritania", fr: "Mauritanie", de: "Mauretanien", it: "Mauritania", ja: "モーリタニア", ko: "모리타니", zh: "毛里塔尼亚", ru: "Мавритания", ar: "موريتانيا" },
  "ms": { en: "Montserrat", pt: "Monserrate", es: "Montserrat", fr: "Montserrat", de: "Montserrat", it: "Montserrat", ja: "モントセラト", ko: "몬트세라트", zh: "蒙特塞拉特", ru: "Монтсеррат", ar: "مونتسرات" },
  "mt": { en: "Malta", pt: "Malta", es: "Malta", fr: "Malte", de: "Malta", it: "Malta", ja: "マルタ", ko: "몰타", zh: "马耳他", ru: "Мальта", ar: "مالطا" },
  "mu": { en: "Mauritius", pt: "Maurícia", es: "Mauricio", fr: "Maurice", de: "Mauritius", it: "Mauritius", ja: "モーリシャス", ko: "모리셔스", zh: "毛里求斯", ru: "Маврикий", ar: "موريشيوس" },
  "mv": { en: "Maldives", pt: "Maldivas", es: "Maldivas", fr: "Maldives", de: "Malediven", it: "Maldive", ja: "モルディブ", ko: "몰디브", zh: "马尔代夫", ru: "Мальдивы", ar: "جزر المالديف" },
  "mw": { en: "Malawi", pt: "Maláui", es: "Malaui", fr: "Malawi", de: "Malawi", it: "Malawi", ja: "マラウイ", ko: "말라위", zh: "马拉维", ru: "Малави", ar: "مالاوي" },
  "mx": { en: "Mexico", pt: "México", es: "México", fr: "Mexique", de: "Mexiko", it: "Messico", ja: "メキシコ", ko: "멕시코", zh: "墨西哥", ru: "Мексика", ar: "المكسيك" },
  "my": { en: "Malaysia", pt: "Malásia", es: "Malasia", fr: "Malaisie", de: "Malaysia", it: "Malesia", ja: "マレーシア", ko: "말레이시아", zh: "马来西亚", ru: "Малайзия", ar: "ماليزيا" },
  "mz": { en: "Mozambique", pt: "Moçambique", es: "Mozambique", fr: "Mozambique", de: "Mosambik", it: "Mozambico", ja: "モザンビーク", ko: "모잠비크", zh: "莫桑比克", ru: "Мозамбик", ar: "موزمبيق" },
  "na": { en: "Namibia", pt: "Namíbia", es: "Namibia", fr: "Namibie", de: "Namibia", it: "Namibia", ja: "ナミビア", ko: "나미비아", zh: "纳米比亚", ru: "Намибия", ar: "ناميبيا" },
  "nc": { en: "New Caledonia", pt: "Nova Caledónia", es: "Nueva Caledonia", fr: "Nouvelle-Calédonie", de: "Neukaledonien", it: "Nuova Caledonia", ja: "ニューカレドニア", ko: "뉴칼레도니아", zh: "新喀里多尼亚", ru: "Новая Каледония", ar: "كاليدونيا الجديدة" },
  "ne": { en: "Niger", pt: "Níger", es: "Níger", fr: "Niger", de: "Niger", it: "Niger", ja: "ニジェール", ko: "니제르", zh: "尼日尔", ru: "Нигер", ar: "النيجر" },
  "nf": { en: "Norfolk Island", pt: "Ilha Norfolk", es: "Isla Norfolk", fr: "Île Norfolk", de: "Norfolkinsel", it: "Isola Norfolk", ja: "ノーフォーク島", ko: "노퍽섬", zh: "诺福克岛", ru: "Остров Норфолк", ar: "جزيرة نورفولك" },
  "ng": { en: "Nigeria", pt: "Nigéria", es: "Nigeria", fr: "Nigéria", de: "Nigeria", it: "Nigeria", ja: "ナイジェリア", ko: "나이지리아", zh: "尼日利亚", ru: "Нигерия", ar: "نيجيريا" },
  "ni": { en: "Nicaragua", pt: "Nicarágua", es: "Nicaragua", fr: "Nicaragua", de: "Nicaragua", it: "Nicaragua", ja: "ニカラグア", ko: "니카라과", zh: "尼加拉瓜", ru: "Никарагуа", ar: "نيكاراغوا" },
  "nl": { en: "Netherlands", pt: "Países Baixos", es: "Países Bajos", fr: "Pays-Bas", de: "Niederlande", it: "Paesi Bassi", ja: "オランダ", ko: "네덜란드", zh: "荷兰", ru: "Нидерланды", ar: "هولندا" },
  "no": { en: "Norway", pt: "Noruega", es: "Noruega", fr: "Norvège", de: "Norwegen", it: "Norvegia", ja: "ノルウェー", ko: "노르웨이", zh: "挪威", ru: "Норвегия", ar: "النرويج" },
  "np": { en: "Nepal", pt: "Nepal", es: "Nepal", fr: "Népal", de: "Nepal", it: "Nepal", ja: "ネパール", ko: "네팔", zh: "尼泊尔", ru: "Непал", ar: "نيبال" },
  "nr": { en: "Nauru", pt: "Nauru", es: "Nauru", fr: "Nauru", de: "Nauru", it: "Nauru", ja: "ナウル", ko: "나우루", zh: "瑙鲁", ru: "Науру", ar: "ناورو" },
  "nu": { en: "Niue", pt: "Niue", es: "Niue", fr: "Niué", de: "Niue", it: "Niue", ja: "ニウエ", ko: "니우에", zh: "纽埃", ru: "Ниуэ", ar: "نييوي" },
  "nz": { en: "New Zealand", pt: "Nova Zelândia", es: "Nueva Zelanda", fr: "Nouvelle-Zélande", de: "Neuseeland", it: "Nuova Zelanda", ja: "ニュージーランド", ko: "뉴질랜드", zh: "新西兰", ru: "Новая Зеландия", ar: "نيوزيلندا" },
  "om": { en: "Oman", pt: "Omã", es: "Omán", fr: "Oman", de: "Oman", it: "Oman", ja: "オマーン", ko: "오만", zh: "阿曼", ru: "Оман", ar: "عمان" },
  "pa": { en: "Panama", pt: "Panamá", es: "Panamá", fr: "Panama", de: "Panama", it: "Panamá", ja: "パナマ", ko: "파나마", zh: "巴拿马", ru: "Панама", ar: "بنما" },
  "pe": { en: "Peru", pt: "Peru", es: "Perú", fr: "Pérou", de: "Peru", it: "Perù", ja: "ペルー", ko: "페루", zh: "秘鲁", ru: "Перу", ar: "بيرو" },
  "pf": { en: "French Polynesia", pt: "Polinésia Francesa", es: "Polinesia Francesa", fr: "Polynésie française", de: "Französisch-Polynesien", it: "Polinesia Francese", ja: "フランス領ポリネシア", ko: "프랑스령 폴리네시아", zh: "法属波利尼西亚", ru: "Французская Полинезия", ar: "بولينزيا الفرنسية" },
  "pg": { en: "Papua New Guinea", pt: "Papua-Nova Guiné", es: "Papua Nueva Guinea", fr: "Papouasie-Nouvelle-Guinée", de: "Papua-Neuguinea", it: "Papua Nuova Guinea", ja: "パプアニューギニア", ko: "파푸아 뉴기니", zh: "巴布亚新几内亚", ru: "Папуа — Новая Гвинея", ar: "بابوا غينيا الجديدة" },
  "ph": { en: "Philippines", pt: "Filipinas", es: "Filipinas", fr: "Philippines", de: "Philippinen", it: "Filippine", ja: "フィリピン", ko: "필리핀", zh: "菲律宾", ru: "Филиппины", ar: "الفلبين" },
  "pk": { en: "Pakistan", pt: "Paquistão", es: "Pakistán", fr: "Pakistan", de: "Pakistan", it: "Pakistan", ja: "パキスタン", ko: "파키스탄", zh: "巴基斯坦", ru: "Пакистан", ar: "باكستان" },
  "pl": { en: "Poland", pt: "Polónia", es: "Polonia", fr: "Pologne", de: "Polen", it: "Polonia", ja: "ポーランド", ko: "폴랜드", zh: "波兰", ru: "Польша", ar: "بولندا" },
  "pm": { en: "Saint Pierre and Miquelon", pt: "Saint Pierre e Miquelon", es: "San Pedro y Miquelón", fr: "Saint-Pierre-et-Miquelon", de: "Saint-Pierre und Miquelon", it: "Saint Pierre e Miquelon", ja: "サンピエール島・ミクロン島", ko: "세인트리에르도,미괘론도", zh: "圣皮埃尔和密克隆", ru: "Сен-Пьер и Микелон", ar: "سان بيير وميكلون" },
  "pn": { en: "Pitcairn Islands", pt: "Ilhas Pitcairn", es: "Pitcairn", fr: "Îles Pitcairn", de: "Pitcairninseln", it: "Isole Pitcairn", ja: "ピトケアン", ko: "핏케언 군도", zh: "皮特凯恩群岛", ru: "Острова Питкэрн", ar: "جزر بيتكيرن" },
  "pr": { en: "Puerto Rico", pt: "Porto Rico", es: "Puerto Rico", fr: "Porto Rico", de: "Puerto Rico", it: "Porto Rico", ja: "プエルトリコ", ko: "푸에르토리코", zh: "波多黎各", ru: "Пуэрто-Рико", ar: "بورتوريكو" },
  "ps": { en: "Palestine", pt: "Territórios palestinos", es: "Palestina", fr: "Palestine", de: "Staat Palästina", it: "Stato di Palestina", ja: "パレスチナ", ko: "팔레스타인", zh: "巴勒斯坦", ru: "Государство Палестина", ar: "فلسطين" },
  "pt": { en: "Portugal", pt: "Portugal", es: "Portugal", fr: "Portugal", de: "Portugal", it: "Portogallo", ja: "ポルトガル", ko: "포르투칼", zh: "葡萄牙", ru: "Португалия", ar: "البرتغال" },
  "pw": { en: "Palau", pt: "Palau", es: "Palau", fr: "Palaos", de: "Palau", it: "Palau", ja: "パラオ", ko: "팔라우", zh: "帕劳", ru: "Палау", ar: "بالاو" },
  "py": { en: "Paraguay", pt: "Paraguai", es: "Paraguay", fr: "Paraguay", de: "Paraguay", it: "Paraguay", ja: "パラグアイ", ko: "파라과이", zh: "巴拉圭", ru: "Парагвай", ar: "باراغواي" },
  "qa": { en: "Qatar", pt: "Qatar", es: "Catar", fr: "Qatar", de: "Katar", it: "Qatar", ja: "カタール", ko: "카타르", zh: "卡塔尔", ru: "Катар", ar: "قطر" },
  "re": { en: "Réunion", pt: "Reunião", es: "Reunión", fr: "Réunion", de: "Réunion", it: "Réunion", ja: "レユニオン", ko: "리유니온", zh: "留尼汪", ru: "Реюньон", ar: "لا ريونيون" },
  "ro": { en: "Romania", pt: "Roménia", es: "Rumanía", fr: "Roumanie", de: "Rumänien", it: "Romania", ja: "ルーマニア", ko: "루마니아", zh: "罗马尼亚", ru: "Румыния", ar: "رومانيا" },
  "rs": { en: "Serbia", pt: "Sérvia", es: "Serbia", fr: "Serbie", de: "Serbien", it: "Serbia", ja: "セルビア", ko: "세르비아", zh: "塞尔维亚", ru: "Сербия", ar: "صربيا" },
  "ru": { en: "Russia", pt: "Rússia", es: "Rusia", fr: "Russie", de: "Russische Föderation", it: "Russia", ja: "ロシア連邦", ko: "러시아연방", zh: "俄罗斯", ru: "Российская Федерация", ar: "روسيا" },
  "rw": { en: "Rwanda", pt: "Ruanda", es: "Ruanda", fr: "Rwanda", de: "Ruanda", it: "Ruanda", ja: "ルワンダ", ko: "르완다", zh: "卢旺达", ru: "Руанда", ar: "رواندا" },
  "sa": { en: "Saudi Arabia", pt: "Arábia Saudita", es: "Arabia Saudita", fr: "Arabie Saoudite", de: "Saudi-Arabien", it: "Arabia Saudita", ja: "サウジアラビア", ko: "사우디아라비아", zh: "沙特阿拉伯", ru: "Саудовская Аравия", ar: "السعودية" },
  "sb": { en: "Solomon Islands", pt: "Ilhas Salomão", es: "Islas Salomón", fr: "Îles Salomon", de: "Salomonen", it: "Isole Salomone", ja: "ソロモン諸島", ko: "솔로몬 아일랜드", zh: "所罗门群岛", ru: "Соломоновы Острова", ar: "جزر سليمان" },
  "sc": { en: "Seychelles", pt: "Seychelles", es: "Seychelles", fr: "Seychelles", de: "Seychellen", it: "Seychelles", ja: "セーシェル", ko: "세이셸", zh: "塞舌尔", ru: "Сейшельские Острова", ar: "سيشل" },
  "sd": { en: "Sudan", pt: "Sudão", es: "Sudán", fr: "Soudan", de: "Sudan", it: "Sudan", ja: "スーダン", ko: "수단", zh: "苏丹", ru: "Судан", ar: "السودان" },
  "se": { en: "Sweden", pt: "Suécia", es: "Suecia", fr: "Suède", de: "Schweden", it: "Svezia", ja: "スウェーデン", ko: "스웨덴", zh: "瑞典", ru: "Швеция", ar: "السويد" },
  "sg": { en: "Singapore", pt: "Singapura", es: "Singapur", fr: "Singapour", de: "Singapur", it: "Singapore", ja: "シンガポール", ko: "싱가포르", zh: "新加坡", ru: "Сингапур", ar: "سنغافورة" },
  "si": { en: "Slovenia", pt: "Eslovénia", es: "Eslovenia", fr: "Slovénie", de: "Slowenien", it: "Slovenia", ja: "スロベニア", ko: "슬로베니아", zh: "斯洛文尼亚", ru: "Словения", ar: "سلوفينيا" },
  "sk": { en: "Slovakia", pt: "Eslováquia", es: "Eslovaquia", fr: "Slovaquie", de: "Slowakei", it: "Slovacchia", ja: "スロバキア", ko: "슬로바키아", zh: "斯洛伐克", ru: "Словакия", ar: "سلوفاكيا" },
  "sl": { en: "Sierra Leone", pt: "Serra Leoa", es: "Sierra Leona", fr: "Sierra Leone", de: "Sierra Leone", it: "Sierra Leone", ja: "シエラレオネ", ko: "시에라 리온", zh: "塞拉利昂", ru: "Сьерра-Леоне", ar: "سيراليون" },
  "sm": { en: "San Marino", pt: "San Marino", es: "San Marino", fr: "Saint-Marin", de: "San Marino", it: "San Marino", ja: "サンマリノ", ko: "산 마리노", zh: "圣马力诺", ru: "Сан-Марино", ar: "سان مارينو" },
  "sn": { en: "Senegal", pt: "Senegal", es: "Senegal", fr: "Sénégal", de: "Senegal", it: "Senegal", ja: "セネガル", ko: "세네갈", zh: "塞内加尔", ru: "Сенегал", ar: "السنغال" },
  "so": { en: "Somalia", pt: "Somália", es: "Somalia", fr: "Somalie", de: "Somalia", it: "Somalia", ja: "ソマリア", ko: "소말리아", zh: "索马里", ru: "Сомали", ar: "الصومال" },
  "sr": { en: "Suriname", pt: "Suriname", es: "Suriname", fr: "Suriname", de: "Suriname", it: "Suriname", ja: "スリナム", ko: "수리남", zh: "苏里南", ru: "Суринам", ar: "سورينام" },
  "ss": { en: "South Sudan", pt: "Sudão do Sul", es: "Sudán del Sur", fr: "Soudan du Sud", de: "Südsudan", it: "Sudan del Sud", ja: "南スーダン", ko: "남수단", zh: "南苏丹", ru: "Южный Судан", ar: "جنوب السودان" },
  "st": { en: "São Tomé and Príncipe", pt: "São Tomé e Príncipe", es: "Santo Tomé y Príncipe", fr: "São Tomé-et-Principe", de: "São Tomé und Príncipe", it: "São Tomé e Príncipe", ja: "サントメ・プリンシペ", ko: "상토메프린시페", zh: "圣多美和普林西比", ru: "Сан-Томе и Принсипи", ar: "ساو تومي وبرينسيب" },
  "sv": { en: "El Salvador", pt: "El Salvador", es: "El Salvador", fr: "El Salvador", de: "El Salvador", it: "El Salvador", ja: "エルサルバドル", ko: "엘살바도르", zh: "萨尔瓦多", ru: "Сальвадор", ar: "السلفادور" },
  "sx": { en: "Sint Maarten", pt: "São Martinho", es: "Sint Maarten (neerlandesa)", fr: "Saint-Martin (partie néerlandaise)", de: "Sint Maarten", it: "Sint Maarten", ja: "シント・マールテン（オランダ領）", ko: "신트마르텐", zh: "荷属圣马丁", ru: "Синт-Мартен", ar: "سانت مارتن (الجزء الهولندي)" },
  "sy": { en: "Syria", pt: "Síria", es: "República Árabe Siria", fr: "Syrie", de: "Syrien, Arabische Republik", it: "Siria", ja: "シリア・アラブ共和国", ko: "시리아", zh: "叙利亚", ru: "Сирия", ar: "سوريا" },
  "sz": { en: "Eswatini", pt: "Essuatíni", es: "Esuatini", fr: "Royaume d'Eswatini", de: "Eswatini", it: "Eswatini", ja: "スワジランド", ko: "스와질란드", zh: "斯威士兰", ru: "Эсватини", ar: "سوازيلاند" },
  "tc": { en: "Turks and Caicos Islands", pt: "Ilhas Turcas e Caicos", es: "Islas Turcas y Caicos", fr: "Îles Turques-et-Caïques", de: "Turks- und Caicosinseln", it: "Isole Turks e Caicos", ja: "タークス・カイコス諸島", ko: "터크스", zh: "特克斯和凯科斯群岛", ru: "Теркс и Кайкос", ar: "جزر توركس وكايكوس" },
  "td": { en: "Chad", pt: "Chade", es: "Chad", fr: "Tchad", de: "Tschad", it: "Ciad", ja: "チャド", ko: "차드", zh: "乍得", ru: "Чад", ar: "تشاد" },
  "tf": { en: "French Southern Territories", pt: "Terras Austrais e Antárticas Francesas", es: "Tierras Australes Francesas", fr: "Terres australes françaises", de: "Französische Süd- und Antarktisgebiete", it: "Territori Francesi del Sud", ja: "フランス領南方・南極地域", ko: "프랑스 남부영토", zh: "法属南部领地", ru: "Французские Южные и Антарктические Территории", ar: "أراض فرنسية جنوبية وأنتارتيكية" },
  "tg": { en: "Togo", pt: "Togo", es: "Togo", fr: "Togo", de: "Togo", it: "Togo", ja: "トーゴ", ko: "토고", zh: "多哥", ru: "Того", ar: "توغو" },
  "th": { en: "Thailand", pt: "Tailândia", es: "Tailandia", fr: "Thaïlande", de: "Thailand", it: "Thailandia", ja: "タイ", ko: "태국", zh: "泰国", ru: "Таиланд", ar: "تايلاند" },
  "tj": { en: "Tajikistan", pt: "Tajiquistão", es: "Tayikistán", fr: "Tadjikistan", de: "Tadschikistan", it: "Tagikistan", ja: "タジキスタン", ko: "타지키스탄", zh: "塔吉克斯坦", ru: "Таджикистан", ar: "طاجيكستان" },
  "tk": { en: "Tokelau", pt: "Tokelau", es: "Tokelau", fr: "Tokelau", de: "Tokelau", it: "Tokelau", ja: "トケラウ", ko: "토켈로", zh: "托克劳", ru: "Токелау", ar: "توكيلاو" },
  "tl": { en: "Timor-Leste", pt: "Timor-Leste", es: "Timor-Leste", fr: "Timor-Leste", de: "Osttimor", it: "Timor Est", ja: "東ティモール", ko: "동티모르", zh: "东帝汶", ru: "Восточный Тимор", ar: "تيمور الشرقية" },
  "tm": { en: "Turkmenistan", pt: "Turquemenistão", es: "Turkmenistán", fr: "Turkménistan", de: "Turkmenistan", it: "Turkmenistan", ja: "トルクメニスタン", ko: "트르크메니스탄", zh: "土库曼斯坦", ru: "Туркмения", ar: "تركمانستان" },
  "tn": { en: "Tunisia", pt: "Tunísia", es: "Túnez", fr: "Tunisie", de: "Tunesien", it: "Tunisia", ja: "チュニジア", ko: "튀니지아", zh: "突尼斯", ru: "Тунис", ar: "تونس" },
  "to": { en: "Tonga", pt: "Tonga", es: "Tonga", fr: "Tonga", de: "Tonga", it: "Tonga", ja: "トンガ", ko: "통가", zh: "汤加", ru: "Тонга", ar: "تونغا" },
  "tr": { en: "Turkey", pt: "Turquia", es: "Turquía", fr: "Turquie", de: "Türkei", it: "Turchia", ja: "トルコ", ko: "터키", zh: "土耳其", ru: "Турция", ar: "تركيا" },
  "tt": { en: "Trinidad and Tobago", pt: "Trindade e Tobago", es: "Trinidad y Tobago", fr: "Trinité-et-Tobago", de: "Trinidad und Tobago", it: "Trinidad e Tobago", ja: "トリニダード・トバゴ", ko: "트리니다드 토바고", zh: "特立尼达和多巴哥", ru: "Тринидад и Тобаго", ar: "ترينيداد وتوباغو" },
  "tv": { en: "Tuvalu", pt: "Tuvalu", es: "Tuvalu", fr: "Tuvalu", de: "Tuvalu", it: "Tuvalu", ja: "ツバル", ko: "트발루", zh: "图瓦卢", ru: "Тувалу", ar: "توفالو" },
  "tw": { en: "Taiwan", pt: "Taiwan", es: "Taiwán", fr: "Taïwan", de: "Taiwan", it: "Repubblica di Cina", ja: "台湾", ko: "중화민국", zh: "中国台湾省", ru: "Тайвань", ar: "تايوان" },
  "tz": { en: "Tanzania", pt: "Tanzânia", es: "Tanzania", fr: "République unie de Tanzanie", de: "Tansania, Vereinigte Republik", it: "Tanzania", ja: "タンザニア", ko: "탄자니아", zh: "坦桑尼亚", ru: "Танзания", ar: "تانزانيا" },
  "ua": { en: "Ukraine", pt: "Ucrânia", es: "Ucrania", fr: "Ukraine", de: "Ukraine", it: "Ucraina", ja: "ウクライナ", ko: "우크라이나", zh: "乌克兰", ru: "Украина", ar: "أوكرانيا" },
  "ug": { en: "Uganda", pt: "Uganda", es: "Uganda", fr: "Ouganda", de: "Uganda", it: "Uganda", ja: "ウガンダ", ko: "우간다", zh: "乌干达", ru: "Уганда", ar: "أوغندا" },
  "us": { en: "United States", pt: "Estados Unidos", es: "Estados Unidos", fr: "États-Unis d'Amérique", de: "Vereinigte Staaten von Amerika", it: "Stati Uniti d'America", ja: "アメリカ合衆国", ko: "미국", zh: "美国", ru: "США", ar: "الولايات المتحدة" },
  "uy": { en: "Uruguay", pt: "Uruguai", es: "Uruguay", fr: "Uruguay", de: "Uruguay", it: "Uruguay", ja: "ウルグアイ", ko: "우루과이", zh: "乌拉圭", ru: "Уругвай", ar: "الأوروغواي" },
  "uz": { en: "Uzbekistan", pt: "Uzbequistão", es: "Uzbekistán", fr: "Ouzbékistan", de: "Usbekistan", it: "Uzbekistan", ja: "ウズベキスタン", ko: "우즈베키스탄", zh: "乌兹别克斯坦", ru: "Узбекистан", ar: "أوزبكستان" },
  "va": { en: "Vatican City", pt: "Santa Sé", es: "Santa Sede", fr: "Saint-Siège (Vatican)", de: "Vatikanstadt", it: "Città del Vaticano", ja: "バチカン市国", ko: "바티칸", zh: "梵蒂冈", ru: "Ватикан", ar: "الفاتيكان" },
  "vc": { en: "Saint Vincent and the Grenadines", pt: "São Vicente e Granadinas", es: "San Vicente y las Granadinas", fr: "Saint-Vincent-et-les-Grenadines", de: "St. Vincent und die Grenadinen", it: "Saint Vincent e Grenadine", ja: "セントビンセントおよびグレナディーン諸島", ko: "세인트 빈센트 그레나딘", zh: "圣文森特和格林纳丁斯", ru: "Сент-Винсент и Гренадины", ar: "سانت فينسنت والغرينادين" },
  "ve": { en: "Venezuela", pt: "Venezuela", es: "Venezuela", fr: "Venezuela", de: "Venezuela", it: "Venezuela", ja: "ベネズエラ・ボリバル共和国", ko: "베네수엘라", zh: "委内瑞拉", ru: "Венесуэла", ar: "فنزويلا" },
  "vg": { en: "British Virgin Islands", pt: "Ilhas Virgens Britânicas", es: "Islas Vírgenes británicas", fr: "Îles vierges britanniques", de: "Britische Jungferninseln", it: "Isole Vergini Britanniche", ja: "イギリス領ヴァージン諸島", ko: "영국령 버진아일랜드", zh: "英属维尔京群岛", ru: "Виргинские Острова (Великобритания)", ar: "جزر العذراء البريطانية" },
  "vi": { en: "U.S. Virgin Islands", pt: "Ilhas Virgens Americanas", es: "Islas Vírgenes de los Estados Unidos", fr: "Îles vierges américaines", de: "Amerikanische Jungferninseln", it: "Isole Vergini Americane", ja: "アメリカ領ヴァージン諸島", ko: "미국령 버진아일랜드", zh: "美属维尔京群岛", ru: "Виргинские Острова (США)", ar: "جزر العذراء الأمريكية" },
  "vn": { en: "Vietnam", pt: "Vietname", es: "Vietnam", fr: "Vietnam", de: "Vietnam", it: "Vietnam", ja: "ベトナム", ko: "베트남", zh: "越南", ru: "Вьетнам", ar: "فيتنام" },
  "vu": { en: "Vanuatu", pt: "Vanuatu", es: "Vanuatu", fr: "Vanuatu", de: "Vanuatu", it: "Vanuatu", ja: "バヌアツ", ko: "바누아투", zh: "瓦努阿图", ru: "Вануату", ar: "فانواتو" },
  "wf": { en: "Wallis and Futuna", pt: "Wallis e Futuna", es: "Wallis y Futuna", fr: "Wallis-et-Futuna", de: "Wallis und Futuna", it: "Wallis e Futuna", ja: "ウォリス・フツナ", ko: "월리스 후트나", zh: "瓦利斯和富图纳", ru: "Уоллис и Футуна", ar: "والس وفوتونا" },
  "ws": { en: "Samoa", pt: "Samoa", es: "Samoa", fr: "Samoa", de: "Samoa", it: "Samoa", ja: "サモア", ko: "사모아", zh: "萨摩亚", ru: "Самоа", ar: "ساموا" },
  "xk": { en: "Kosovo", pt: "Kosovo", es: "Kosovo", fr: "Kosovo", de: "Kosovo", it: "Kosovo", ja: "コソボ", ko: "코소보", zh: "科索沃", ru: "Косово", ar: "كوسوفو" },
  "ye": { en: "Yemen", pt: "Iémen", es: "Yemen", fr: "Yémen", de: "Jemen", it: "Yemen", ja: "イエメン", ko: "예멘", zh: "也门", ru: "Йемен", ar: "اليمن" },
  "yt": { en: "Mayotte", pt: "Mayotte", es: "Mayotte", fr: "Mayotte", de: "Mayotte", it: "Mayotte", ja: "マヨット", ko: "마요트", zh: "马约特", ru: "Майотта", ar: "مايوت" },
  "za": { en: "South Africa", pt: "África do Sul", es: "Sudáfrica", fr: "Afrique du Sud", de: "Südafrika", it: "Sudafrica", ja: "南アフリカ", ko: "남아프리카", zh: "南非", ru: "ЮАР", ar: "جنوب أفريقيا" },
  "zm": { en: "Zambia", pt: "Zâmbia", es: "Zambia", fr: "Zambie", de: "Sambia", it: "Zambia", ja: "ザンビア", ko: "잠비아", zh: "赞比亚", ru: "Замбия", ar: "زامبيا" },
  "zw": { en: "Zimbabwe", pt: "Zimbábue", es: "Zimbabue", fr: "Zimbabwe", de: "Simbabwe", it: "Zimbabwe", ja: "ジンバブエ", ko: "짐바브웨 공화국", zh: "津巴布韦", ru: "Зимбабве", ar: "زيمبابوي" },
};

/** Traduz o nome de um país pelo seu código ISO e idioma (fallback: inglês). */
export function translateCountry(
  iso: string,
  locale: string = "en",
): string {
  const translations = COUNTRY_TRANSLATIONS[iso];
  if (!translations) return "";
  return translations[locale as CountryTranslateLocale] ?? translations.en;
}
