/**
 * Mapeamento de nomes de ícones Hugeicons para os caminhos dos arquivos SVG.
 * Os arquivos SVG estão em src/lib/assets/hugeicons/
 * Generated by `npm run generate:hugeicons` — não edite manualmente.
 */

import advertisiment from "$lib/assets/hugeicons/advertisiment-stroke-rounded.svg";
import album01 from "$lib/assets/hugeicons/album-01-stroke-rounded.svg";
import alertCircle from "$lib/assets/hugeicons/alert-circle-stroke-rounded.svg";
import analytics01 from "$lib/assets/hugeicons/analytics-01-stroke-rounded.svg";
import appWindow from "$lib/assets/hugeicons/app-window-stroke-rounded.svg";
import arrowDown01 from "$lib/assets/hugeicons/arrow-down-01-stroke-rounded.svg";
import arrowLeft01 from "$lib/assets/hugeicons/arrow-left-01-stroke-rounded.svg";
import arrowRight01 from "$lib/assets/hugeicons/arrow-right-01-stroke-rounded.svg";
import badgeCheck from "$lib/assets/hugeicons/badge-check-stroke-rounded.svg";
import bedDouble from "$lib/assets/hugeicons/bed-double-stroke-rounded.svg";
import calendar03 from "$lib/assets/hugeicons/calendar-03-stroke-rounded.svg";
import cancel01 from "$lib/assets/hugeicons/cancel-01-stroke-rounded.svg";
import checkmarkCircle02 from "$lib/assets/hugeicons/checkmark-circle-02-stroke-rounded.svg";
import chevronLeft from "$lib/assets/hugeicons/chevron-left-stroke-rounded.svg";
import chevronRight from "$lib/assets/hugeicons/chevron-right-stroke-rounded.svg";
import component from "$lib/assets/hugeicons/component-stroke-rounded.svg";
import copy from "$lib/assets/hugeicons/copy-stroke-rounded.svg";
import dashboardBrowsing from "$lib/assets/hugeicons/dashboard-browsing-stroke-rounded.svg";
import dashboardCircleAdd from "$lib/assets/hugeicons/dashboard-circle-add-stroke-rounded.svg";
import dashboardSquare01 from "$lib/assets/hugeicons/dashboard-square-01-stroke-rounded.svg";
import delete02 from "$lib/assets/hugeicons/delete-02-stroke-rounded.svg";
import documentCode from "$lib/assets/hugeicons/document-code-stroke-rounded.svg";
import eye from "$lib/assets/hugeicons/eye-stroke-rounded.svg";
import eyeOff from "$lib/assets/hugeicons/eye-off-stroke-rounded.svg";
import facebook01 from "$lib/assets/hugeicons/facebook-01-stroke-rounded.svg";
import file01 from "$lib/assets/hugeicons/file-01-stroke-rounded.svg";
import fileCode from "$lib/assets/hugeicons/file-code-stroke-rounded.svg";
import folder01 from "$lib/assets/hugeicons/folder-01-stroke-rounded.svg";
import form from "$lib/assets/hugeicons/form-stroke-rounded.svg";
import galleryThumbnails from "$lib/assets/hugeicons/gallery-thumbnails-stroke-rounded.svg";
import global from "$lib/assets/hugeicons/global-stroke-rounded.svg";
import globalEditing from "$lib/assets/hugeicons/global-editing-stroke-rounded.svg";
import google from "$lib/assets/hugeicons/google-stroke-rounded.svg";
import gridTable from "$lib/assets/hugeicons/grid-table-stroke-rounded.svg";
import gripVertical from "$lib/assets/hugeicons/grip-vertical-stroke-rounded.svg";
import heartAdd from "$lib/assets/hugeicons/heart-add-stroke-rounded.svg";
import heartRemove from "$lib/assets/hugeicons/heart-remove-stroke-rounded.svg";
import helpCircle from "$lib/assets/hugeicons/help-circle-stroke-rounded.svg";
import home01 from "$lib/assets/hugeicons/home-01-stroke-rounded.svg";
import informationCircle from "$lib/assets/hugeicons/information-circle-stroke-rounded.svg";
import link01 from "$lib/assets/hugeicons/link-01-stroke-rounded.svg";
import linkedin01 from "$lib/assets/hugeicons/linkedin-01-stroke-rounded.svg";
import loaderPinwheel from "$lib/assets/hugeicons/loader-pinwheel-stroke-rounded.svg";
import location01 from "$lib/assets/hugeicons/location-01-stroke-rounded.svg";
import lockPassword from "$lib/assets/hugeicons/lock-password-stroke-rounded.svg";
import login02 from "$lib/assets/hugeicons/login-02-stroke-rounded.svg";
import logout01 from "$lib/assets/hugeicons/logout-01-stroke-rounded.svg";
import mail01 from "$lib/assets/hugeicons/mail-01-stroke-rounded.svg";
import manager from "$lib/assets/hugeicons/manager-stroke-rounded.svg";
import mapPinned from "$lib/assets/hugeicons/map-pinned-stroke-rounded.svg";
import maping from "$lib/assets/hugeicons/maping-stroke-rounded.svg";
import maximizeScreen from "$lib/assets/hugeicons/maximize-screen-stroke-rounded.svg";
import menu07 from "$lib/assets/hugeicons/menu-07-stroke-rounded.svg";
import message01 from "$lib/assets/hugeicons/message-01-stroke-rounded.svg";
import minusSign from "$lib/assets/hugeicons/minus-sign-stroke-rounded.svg";
import money01 from "$lib/assets/hugeicons/money-01-stroke-rounded.svg";
import moon02 from "$lib/assets/hugeicons/moon-02-stroke-rounded.svg";
import moreHorizontal from "$lib/assets/hugeicons/more-horizontal-stroke-rounded.svg";
import moreHorizontalCircle01 from "$lib/assets/hugeicons/more-horizontal-circle-01-stroke-rounded.svg";
import necklace from "$lib/assets/hugeicons/necklace-stroke-rounded.svg";
import package_ from "$lib/assets/hugeicons/package-stroke-rounded.svg";
import payment01 from "$lib/assets/hugeicons/payment-01-stroke-rounded.svg";
import plusSign from "$lib/assets/hugeicons/plus-sign-stroke-rounded.svg";
import presentation02 from "$lib/assets/hugeicons/presentation-02-stroke-rounded.svg";
import profile02 from "$lib/assets/hugeicons/profile-02-stroke-rounded.svg";
import refresh from "$lib/assets/hugeicons/refresh-stroke-rounded.svg";
import rocket01 from "$lib/assets/hugeicons/rocket-01-stroke-rounded.svg";
import search01 from "$lib/assets/hugeicons/search-01-stroke-rounded.svg";
import setting07 from "$lib/assets/hugeicons/setting-07-stroke-rounded.svg";
import share01 from "$lib/assets/hugeicons/share-01-stroke-rounded.svg";
import shoppingBasket01 from "$lib/assets/hugeicons/shopping-basket-01-stroke-rounded.svg";
import shoppingCartAdd01 from "$lib/assets/hugeicons/shopping-cart-add-01-stroke-rounded.svg";
import shoppingCartRemove01 from "$lib/assets/hugeicons/shopping-cart-remove-01-stroke-rounded.svg";
import sidebarLeft from "$lib/assets/hugeicons/sidebar-left-stroke-rounded.svg";
import smartPhone02 from "$lib/assets/hugeicons/smart-phone-02-stroke-rounded.svg";
import sparkles from "$lib/assets/hugeicons/sparkles-stroke-rounded.svg";
import star from "$lib/assets/hugeicons/star-stroke-rounded.svg";
import starHalf from "$lib/assets/hugeicons/star-half-stroke-rounded.svg";
import sun01 from "$lib/assets/hugeicons/sun-01-stroke-rounded.svg";
import tick02 from "$lib/assets/hugeicons/tick-02-stroke-rounded.svg";
import unfoldMore from "$lib/assets/hugeicons/unfold-more-stroke-rounded.svg";
import userMultiple from "$lib/assets/hugeicons/user-multiple-stroke-rounded.svg";
import userSearch01 from "$lib/assets/hugeicons/user-search-01-stroke-rounded.svg";
import user from "$lib/assets/hugeicons/user-stroke-rounded.svg";
import videoReplay from "$lib/assets/hugeicons/video-replay-stroke-rounded.svg";
import wallet01 from "$lib/assets/hugeicons/wallet-01-stroke-rounded.svg";
import whatsapp from "$lib/assets/hugeicons/whatsapp-stroke-rounded.svg";

export const hugeiconsSvg: Record<string, string> = {
    "advertisiment": advertisiment,
    "album-01": album01,
    "alert-circle": alertCircle,
    "analytics-01": analytics01,
    "app-window": appWindow,
    "arrow-down-01": arrowDown01,
    "arrow-left-01": arrowLeft01,
    "arrow-right-01": arrowRight01,
    "badge-check": badgeCheck,
    "bed-double": bedDouble,
    "calendar-03": calendar03,
    "cancel-01": cancel01,
    "checkmark-circle-02": checkmarkCircle02,
    "chevron-left": chevronLeft,
    "chevron-right": chevronRight,
    "component": component,
    "copy": copy,
    "dashboard-browsing": dashboardBrowsing,
    "dashboard-circle-add": dashboardCircleAdd,
    "dashboard-square-01": dashboardSquare01,
    "delete-02": delete02,
    "document-code": documentCode,
    "eye": eye,
    "eye-off": eyeOff,
    "facebook-01": facebook01,
    "file-01": file01,
    "file-code": fileCode,
    "folder-01": folder01,
    "form": form,
    "gallery-thumbnails": galleryThumbnails,
    "global": global,
    "global-editing": globalEditing,
    "google": google,
    "grid-table": gridTable,
    "grip-vertical": gripVertical,
    "heart-add": heartAdd,
    "heart-remove": heartRemove,
    "help-circle": helpCircle,
    "home-01": home01,
    "information-circle": informationCircle,
    "link-01": link01,
    "linkedin-01": linkedin01,
    "loader-pinwheel": loaderPinwheel,
    "location-01": location01,
    "lock-password": lockPassword,
    "login-02": login02,
    "logout-01": logout01,
    "mail-01": mail01,
    "manager": manager,
    "map-pinned": mapPinned,
    "maping": maping,
    "maximize-screen": maximizeScreen,
    "menu-07": menu07,
    "message-01": message01,
    "minus-sign": minusSign,
    "money-01": money01,
    "moon-02": moon02,
    "more-horizontal": moreHorizontal,
    "more-horizontal-circle-01": moreHorizontalCircle01,
    "necklace": necklace,
    "package": package_,
    "payment-01": payment01,
    "plus-sign": plusSign,
    "presentation-02": presentation02,
    "profile-02": profile02,
    "refresh": refresh,
    "rocket-01": rocket01,
    "search-01": search01,
    "setting-07": setting07,
    "share-01": share01,
    "shopping-basket-01": shoppingBasket01,
    "shopping-cart-add-01": shoppingCartAdd01,
    "shopping-cart-remove-01": shoppingCartRemove01,
    "sidebar-left": sidebarLeft,
    "smart-phone-02": smartPhone02,
    "sparkles": sparkles,
    "star": star,
    "star-half": starHalf,
    "sun-01": sun01,
    "tick-02": tick02,
    "unfold-more": unfoldMore,
    "user-multiple": userMultiple,
    "user-search-01": userSearch01,
    "user": user,
    "video-replay": videoReplay,
    "wallet-01": wallet01,
    "whatsapp": whatsapp,
};

export type HugeiconsSvgName = keyof typeof hugeiconsSvg;
