import type { CardFlightProps } from "../types";

const items: CardFlightProps[] = [
  {
    id: 1,
    logo: "",
    imageUrl:
      "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=1170&auto=format&fit=crop",
    title: "TAAG Luanda — Lubango",
    origin: "Luanda",
    destination: "Lubango",
    departureTime: "01 Mar, 08:30",
    arrivalTime: "01 Mar, 09:45",
    duration: "1h 15min",
    type: "FLIGHT",
    country: "ao",
    price: "85.000",
    currency: "Kz",
    content:
      "Voo directo com partida às 08:30 e chegada estimada às 09:45, com 20kg de bagagem incluídos.",
    isFavorite: true,
    buttonBuyText: "Reservar",
    onClickBuy: (id: string | number) => alert(`Reservar viagem ${id}`),
    onClickFavorite: (id: string | number) => alert(`Favoritar viagem ${id}`),
    tags: [
      { icon: "Airplane01Icon", text: "Voo directo" },
      { icon: "Ticket01Icon", text: "20kg bagagem" },
      { icon: "AirplaneSeatIcon", text: "Executiva" },
    ],
  },
  {
    id: 2,
    imageUrl:
      "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1170&auto=format&fit=crop",
    title: "Interprovincial Benguela",
    origin: "Luanda",
    destination: "Benguela",
    departureTime: "05 Mar, 06:00",
    arrivalTime: "05 Mar, 12:30",
    duration: "6h 30min",
    type: "INTERPROVINCIAL",
    country: "ao",
    price: "32.500",
    currency: "Kz",
    content:
      "Viagem rodoviária interprovincial com paragem em Catumbela, ar condicionado e lanche a bordo incluídos.",
    isFavorite: false,
    buttonBuyText: "Reservar",
    onClickBuy: (id: string | number) => alert(`Reservar viagem ${id}`),
    onClickFavorite: (id: string | number) => alert(`Favoritar viagem ${id}`),
    tags: [
      { icon: "Bus01Icon", text: "Rodoviária" },
      { icon: "MapPinnedIcon", text: "Catumbela" },
    ],
  },
  {
    id: 3,
    title: "Sonangol Luanda — Soyo",
    origin: "Luanda",
    destination: "Soyo",
    departureTime: "08 Mar, 07:15",
    arrivalTime: "08 Mar, 08:20",
    duration: "1h 05min",
    type: "FLIGHT",
    country: "ao",
    price: "48.000",
    currency: "Kz",
    content:
      "Voo doméstico para a região do Baixo Congo, com bagagem incluída e transfer para o centro da cidade.",
    isFavorite: true,
    buttonBuyText: "Reservar",
    onClickBuy: (id: string | number) => alert(`Reservar viagem ${id}`),
    onClickFavorite: (id: string | number) => alert(`Favoritar viagem ${id}`),
    tags: [
      { icon: "AirplaneTakeOff01Icon", text: "Doméstico" },
      { icon: "Clock01Icon", text: "Partida cedo" },
    ],
  },
  {
    id: 4,
    title: "TAP Luanda — Lisboa",
    origin: "Luanda",
    destination: "Lisboa",
    departureTime: "12 Mar, 22:40",
    arrivalTime: "13 Mar, 06:05",
    duration: "7h 25min",
    type: "FLIGHT",
    country: "ao",
    price: "420.000",
    currency: "Kz",
    content:
      "Voo internacional com escala em Casablanca e ligação directa para Lisboa, com menus a bordo e check-in prioritário.",
    isFavorite: false,
    buttonBuyText: "Reservar",
    onClickBuy: (id: string | number) => alert(`Reservar viagem ${id}`),
    onClickFavorite: (id: string | number) => alert(`Favoritar viagem ${id}`),
    tags: [
      { icon: "GlobalIcon", text: "Internacional" },
      { icon: "Exchange01Icon", text: "1 escala" },
    ],
  },
  {
    id: 5,
    title: "Nmw Lubango — Huambo",
    origin: "Lubango",
    destination: "Huambo",
    departureTime: "15 Mar, 09:00",
    arrivalTime: "15 Mar, 10:10",
    duration: "1h 10min",
    type: "FLIGHT",
    country: "ao",
    price: "27.000",
    currency: "Kz",
    content:
      "Ligação aérea no planalto central com aviões de 30 lugares e bagagem de 15kg incluída.",
    isFavorite: false,
    buttonBuyText: "Reservar",
    onClickBuy: (id: string | number) => alert(`Reservar viagem ${id}`),
    onClickFavorite: (id: string | number) => alert(`Favoritar viagem ${id}`),
    tags: [
      { icon: "Airplane02Icon", text: "30 lugares" },
      { icon: "Ticket01Icon", text: "15kg bagagem" },
    ],
  },
];

export default items;