import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const cssFile = path.join(repoRoot, "icons.css");
const outputFile = path.join(repoRoot, "src/lib/components/ui/image/icons.ts");

const css = await readFile(cssFile, "utf-8");
const slugs = [
	...new Set(
		[...css.matchAll(/\.hgi-stroke\.hgi-([a-z0-9-]+)::before/g)].map((m) => m[1]),
	),
].sort((a, b) => a.localeCompare(b, "en"));

const toCode = (slug) =>
	`${slug
		.split("-")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("")}Icon`;

/**
 * `hgi-music-3` e `hgi-music3` colidem em `Music3Icon`. Nesses casos
 * preservamos o hífen no código (`Music-3Icon`) e, se ainda assim colidir,
 * acrescentamos um sufixo numérico.
 */
const toDisambiguatedCode = (slug) =>
	slug
		.split("-")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("-") + "Icon";

const uniqueCode = (slug, used) => {
	const candidates = [toCode(slug), toDisambiguatedCode(slug)];
	for (const base of candidates) {
		if (!used.has(base)) return base;
	}
	const stem = toDisambiguatedCode(slug).replace(/Icon$/, "");
	for (let n = 2; ; n++) {
		const candidate = `${stem}${n}Icon`;
		if (!used.has(candidate)) return candidate;
	}
};

const used = new Set();
const entries = slugs.map((slug) => {
	const code = uniqueCode(slug, used);
	used.add(code);
	return { className: `hgi hgi-stroke hgi-${slug}`, code };
});

const lines = [
	"/**",
	" * Ícones Hugeicons (fonte) disponíveis.",
	" * `className` são as classes CSS do icon font; `code` é o nome usado na prop `icon`.",
	" * Generated by `npm run generate:icons` — não edite manualmente.",
	" */",
	"",
	"export interface IconData {",
	"\tclassName: string;",
	"\tcode: string;",
	"}",
	"",
	"export const items = [",
	...entries.map(
		({ className, code }) => `\t{ className: "${className}", code: "${code}" },`,
	),
	"] as const satisfies readonly IconData[];",
	"",
	"export type HugeiconsIconName = (typeof items)[number][\"code\"];",
	"",
	"export const icons: Record<HugeiconsIconName, string> = Object.fromEntries(",
	"\titems.map((item) => [item.code, item.className]),",
	") as Record<HugeiconsIconName, string>;",
	"",
	"export const defaultIcon: HugeiconsIconName = \"AlertCircleIcon\";",
	"",
];

await writeFile(outputFile, lines.join("\n"), "utf-8");
console.log(`Generated ${entries.length} icons in ${outputFile}`);
